apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: {{ template "vhss.fullname" . }}
  labels:
    app: {{ template "vhss.name" . }}
    chart: {{ template "vhss.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ template "vhss.name" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ template "vhss.name" . }}
        release: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["/usr/bin/top"]
          tty: true
          env:
          - name: "TERM"
            value: "dumb"
