---
dependencies:
- name: nw
  version: 0.1.0
  repository: file://../nw
- name: vspgwc
  version: 0.1.0
  repository: file://../vspgwc
- name: vspgwu
  version: 0.1.0
  repository: file://../vspgwu

