# Default values for vepc-single.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

busyboxImage:
  repository: busybox
  tag: latest
  pullPolicy: IfNotPresent

nodeSelector: {}

tolerations: []

affinity: {}
