---
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: {{ template "vhssdb.fullname" . }}
  labels:
    app: {{ template "vhssdb.name" . }}
    chart: {{ template "vhssdb.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  annotations:
    networks: '[
          {"name": "{{.Release.Name}}-hssdb-net"}
  ]'
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ template "vhssdb.name" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ template "vhssdb.name" . }}
        release: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          
