
apiVersion: v1
kind: Service
metadata:
  name: {{ template "vspgwc.fullname" . }}-s11spgw
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ template "vspgwc.name" . }}
    chart: {{ template "vspgwc.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.services.s11spgwServiceType }}
  ports:
  - name: s11spgwc
{{ toYaml .Values.services.s11spgwc | indent 4 }}
  selector:
    app: {{ template "vspgwc.name" . }}
    release: {{ .Release.Name }}
