# Default values for vmme.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: ngick8stesting/c3po-mme
  tag: configmaps-debug
  pullPolicy: IfNotPresent

services:
  s11mmeServiceType: ClusterIP
  s11mme:
    port: 21
    
namespace: default

nodeSelector: {}

tolerations: []

affinity: {}
